version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:lts-noble
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: frete_rapido
